In [275]:
import pandas as pd
import numpy as np

# to store 1 directional data using pandas

# series datastructure

In [276]:
l1=["a","b","c","d","e"]
s1=pd.Series(l1)

s1

0    a
1    b
2    c
3    d
4    e
dtype: object

In [277]:
ar2= np.random.randint(20,25, size=(10))
ar2

array([23, 22, 22, 21, 20, 22, 23, 21, 23, 22], dtype=int32)

In [278]:
s2= pd.Series(ar2)
s2

0    23
1    22
2    22
3    21
4    20
5    22
6    23
7    21
8    23
9    22
dtype: int32

In [279]:
s3=pd.Series(np.random.randint(30,35, size=10))
s3

0    33
1    31
2    33
3    32
4    32
5    32
6    30
7    30
8    30
9    34
dtype: int32

In [280]:
print(s2+s3)

0    56
1    53
2    55
3    53
4    52
5    54
6    53
7    51
8    53
9    56
dtype: int32

# DataFrame

In [281]:
students=["saksham","sukisuki","chustab","simret","newarni"]
roll=['001','002','003','004','005']
scores=['40',"20","19","30","18"]
record={
    "Students":students,
    "Roll no":roll,
    "Score":scores
}

In [282]:
record

{'Students': ['saksham', 'sukisuki', 'chustab', 'simret', 'newarni'],
 'Roll no': ['001', '002', '003', '004', '005'],
 'Score': ['40', '20', '19', '30', '18']}

In [283]:
record_df=pd.DataFrame(record)
record_df

   Students Roll no Score
0   saksham     001    40
1  sukisuki     002    20
2   chustab     003    19
3    simret     004    30
4   newarni     005    18

In [284]:
record_df.set_index(["Roll no"])

         Students Score
Roll no
001       saksham    40
002      sukisuki    20
003       chustab    19
004        simret    30
005       newarni    18

In [285]:
d1= {
    "A":[2,3,4,5,6],
    "B":[12,13,14,15,16],
    "C":[14,16,17,18,28],
    "D":[12,14,11,12,44]
}
df_=pd.DataFrame(d1)
df_

   A   B   C   D
0  2  12  14  12
1  3  13  16  14
2  4  14  17  11
3  5  15  18  12
4  6  16  28  44

### to see columns

In [286]:
df_.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

### accessing desired column

In [287]:
df_[["A", "B"]]

   A   B
0  2  12
1  3  13
2  4  14
3  5  15
4  6  16

In [288]:
df_["E"]=df_["A"]+df_["B"]+df_["C"]+df_["D"]
df_["F"]=df_["E"]/4
df_

   A   B   C   D   E     F
0  2  12  14  12  40  10.0
1  3  13  16  14  46  11.5
2  4  14  17  11  46  11.5
3  5  15  18  12  50  12.5
4  6  16  28  44  94  23.5

### info()

In [289]:
df_.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
 3   D       5 non-null      int64
 4   E       5 non-null      int64
 5   F       5 non-null      float64
dtypes: float64(1), int64(5)
memory usage: 372.0 bytes

In [290]:
dic2={
    "Students":["student1",
    "student2",
    "student2",
    "student3",
    "student5"],
    "Roll":['1','6','6',np.nan,'7'],
    "Gender":["Male","Female","Female",np.nan,"Male"],
    "Marks Obtained":[22,67,67,np.nan,71]
}
dic2

{'Students': ['student1', 'student2', 'student2', 'student3', 'student5'],
 'Roll': ['1', '6', '6', nan, '7'],
 'Gender': ['Male', 'Female', 'Female', nan, 'Male'],
 'Marks Obtained': [22, 67, 67, nan, 71]}

In [291]:
dic2_df=pd.DataFrame(dic2)
dic2_df

   Students Roll  Gender  Marks Obtained
0  student1    1    Male            22.0
1  student2    6  Female            67.0
2  student2    6  Female            67.0
3  student3  NaN     NaN             NaN
4  student5    7    Male            71.0

In [292]:
dic2_df.isnull().sum()

Students          0
Roll              1
Gender            1
Marks Obtained    1
dtype: int64

In [293]:
dic2_df.duplicated().sum()

np.int64(1)

In [294]:
dic2_df.drop_duplicates()

   Students Roll  Gender  Marks Obtained
0  student1    1    Male            22.0
1  student2    6  Female            67.0
3  student3  NaN     NaN             NaN
4  student5    7    Male            71.0

In [297]:
dic2_df.dropna()

   Students Roll  Gender  Marks Obtained
0  student1    1    Male            22.0
1  student2    6  Female            67.0
2  student2    6  Female            67.0
4  student5    7    Male            71.0